[package]
name = "gempa-bmkg"
version = "0.1.0"
edition = "2021"

[dependencies]
# HTTP client async. Pakai rustls biar tidak perlu install OpenSSL di macOS/Linux.
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
tokio      = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
